name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: vigoux/languagetool.nvim:latest

    steps:
    - uses: actions/checkout@v1
    - name: Link plugin
      run: ln -s $GITHUB_WORKSPACE/LanguageTool.nvim /root/.local/share/nvim/site/pack/vigoux/start/LanguageTool.nvim
    - name: Run tests
      run: nvim +"Vader! /root/.local/share/nvim/site/pack/vigoux/start/LanguageTool.nvim/tests/*"
