name: Setup tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with: 
        java-version: '1.8'
    - name: Donwload LanguageTool
      run: wget https://languagetool.org/download/LanguageTool-4.6.zip
    - name: Unzip LanguageTool
      run: unzip https://languagetool.org/download/LanguageTool-4.6.zip
