name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: vigoux/languagetool.nvim:latest

    steps:
    - name: Download repo and checkout commit
      run: |
        git clone https://github.com/$GITHUB_REPOSITORY.git /home/repo
        cd /home/repo
        git checkout --progress --force $GITHUB_SHA
    - name: Link plugin
      run: ln -s /home/repo /root/.local/share/nvim/site/pack/vigoux/start/LanguageTool.nvim
    - name: Run tests
      run: nvim -c "Vader! /home/repo/tests/*" > /dev/null
